### ISSUE TITLE
max_duration not working on videos (API issue)

### ISSUE THREAD

**Issue by stilllife00** [pexels/pexels-javascript#1]
```
curl -H "Authorization: XXXX"   "https://api.pexels.com/videos/search?query=nature&per_page=1&max_duration=10"
```

Returned videos have various duration, no matter the filter

**Comment by josephfarina** [comment]
Thanks for your report! Our backend team will investigate this shortly.

**Comment by Kadaaran** [comment]
Hey @stilllife00 
Sorry for getting back to you so late, a fix is on its way to be done. 
Thank you for reporting this issue 🙏

**Comment by hersh-kat** [comment]
I'm experiencing the same issue when using the "min_duration" filter. I'm currently calling this with the JavaScript Library. Not sure if this is an issue with the library or the entire API endpoint.

**Comment by Kadaaran** [comment]
@hersh-kat It's an issue with the endpoint itself. Thanks for reporting as well 👍

**Comment by FRANK-AND-FREE** [comment]
Hi there, is there a fix on the way in the meantime? I have the feeling that most filter don't work at the moment. "min_width" and "min_height" don't have an effect, either, as I could observe.
The API docs are missing things, too, as it seems. For example is the "locale" query parameter also available for video queries, but is only documented for photo requests.
And I have a question concerning the API, too. Can you actually filter videos by their orientation (landscape, portrait, square) in the query, just as you can on pexels.com website?

Nevertheless, thank you Pexels team for your great website!
Best regards,
Frank

**Comment by Kadaaran** [comment]
Hi @FRANK-AND-FREE ! 👋 
Thank you for reporting this as well. To give you more context: it's on our radar and we're working on a fix, the filter issue only affect the videos not the photos, thank you for your patience.

>The API docs are missing things, too, as it seems. For example is the "locale" query parameter also available for video queries, but is only documented for photo requests.
It is indeed, thank you for pointing this out, it will be updated shortly !

>And I have a question concerning the API, too. Can you actually filter videos by their orientation (landscape, portrait, square) in the query, just as you can on pexels.com website?
It isn't yet implemented in the API, but we will discuss it internally with the team.

Best regards and thank you again for your patience ✨

**Comment by josephfarina** [comment]
Closing since it appears to be fixed. Please reopen it in the future if it hasn't.
