### ISSUE TITLE
{ status: 400, code: 'No query param given' }

### ISSUE THREAD

**Issue by photocherkaoui** [pexels/pexels-javascript#3]
Hi,
 In the following file, I get { status: 400, code: 'No query param given' } error.

   `const axios = require('axios');
const {createClient} = require('pexels');

const client = createClient(myKey);

const imageService=async(image)=>{
    try {
        
        const res=await client.photos.search({ image, per_page: 1 });
       console.log(res);
       return res.url;
    } catch (error) {
        console.log(error)   
    }
}
imageService('lion')

module.exports= imageService;
`
I use the latest version in Windows 10
Thank you for your recommandations

**Comment by josephfarina** [comment]
Hi @photocherkaoui,

You need to pass a `query` parameter to the search function instead of an image parameter:`client.photos.search({ query: image, per_page: 1 })`
