### ISSUE TITLE
getting issue of "process is not defined"

### ISSUE THREAD

**Issue by ssubham** [pexels/pexels-javascript#31]
Hi, 
I am getting issue of "process is not defined" when using in my apllication with NPM package.
![isse](https://user-images.githubusercontent.com/3177615/161914992-f80cf8ef-80bf-46ac-a8b5-c0c1cab5d2ce.jpg)

I have used 
`import { createClient } from 'pexels';
const client = createClient('api-key');`

Let me know how it can be fixed.

**Comment by davidkhierl** [comment]
having the same problem as well, package is broken

**Comment by dominggo1999** [comment]
For vite users, I resolved this using [@rollup/plugin-replace](https://www.npmjs.com/package/@rollup/plugin-replace)
Maybe webpack  has something similar to this.

vite.config.js

    import replace from '@rollup/plugin-replace';
    
    export  default  defineConfig({
        	plugins: [
        	    replace({
        
    		        preventAssignment:  true,
    	    
    		       'process.env.API_KEY': {},
    	    
    		       'require("isomorphic-fetch");':  'import "isomorphic-fetch";',
                      })
        	   ]
        })
