### ISSUE TITLE
Update isomorphic-fetch dep

### ISSUE THREAD

**Issue by YuriGor** [pexels/pexels-javascript#6]
Hi, npm is complaining:
```
npm audit
# npm audit report

node-fetch  <=2.6.0 || 3.0.0-beta.1 - 3.0.0-beta.8
Denial of Service - https://npmjs.com/advisories/1556
No fix available
node_modules/isomorphic-fetch/node_modules/node-fetch
  isomorphic-fetch  2.0.0 - 2.2.1
  Depends on vulnerable versions of node-fetch
  node_modules/isomorphic-fetch
    pexels  *
    Depends on vulnerable versions of isomorphic-fetch
    node_modules/pexels

```
isomorphic-fetch of v3 has already been updated [to fixed node-fetch version 2.6.1](https://github.com/matthew-andrews/isomorphic-fetch/blob/master/package.json)
So could we also bump to latest isomorphic-fetch?
Here is a [release notes for v3](https://github.com/matthew-andrews/isomorphic-fetch/issues/192), a bit hidden yet.

**Comment by josephfarina** [comment]
Thanks for creating the issue. I will update this asap.
